#!/bin/bash
# gen-nginx.sh — Scan network, generate nginx reverse-proxy config for Luckfox devices
# Usage: sudo ./gen-nginx.sh [interface]

SCANNER="$(dirname "$0")/ipscanner"
IFACE="${1:-eth0}"
JSON_TMP="/tmp/ipscan_result.json"
NGINX_PROXY="/etc/nginx/conf.d/ipscan-proxy.conf"
NGINX_LANDING="/etc/nginx/conf.d/ipscan-landing.conf"
WEBROOT="/var/www/ipscan"

# ── 1. Scan network ───────────────────────────────────────────────────────────
echo "[1/4] Scanning $IFACE ..."
"$SCANNER" -i "$IFACE" -j "$JSON_TMP"

# ── 2. Generate nginx proxy config ───────────────────────────────────────────
echo "[2/4] Generating nginx proxy config ..."

python3 << PYEOF
import json, sys

with open('$JSON_TMP') as f:
    hosts = json.load(f)

devices = [h for h in hosts
           if 'Line' in h.get('comment','') and '[GM' in h.get('comment','')]

if not devices:
    print("  No Line/GM devices found.")
    sys.exit(0)

lines = ["# Auto-generated by gen-nginx.sh — do not edit manually\n"]
for h in devices:
    ip      = h['ip']
    comment = h['comment']
    last    = int(ip.split('.')[-1])
    port    = 9000 + last
    lines.append("""
# {comment}  ({ip})
server {{
    listen {port};
    server_name _;
    location / {{
        proxy_pass         http://{ip}:8000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    \$http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_set_header   Host       \$host;
        proxy_read_timeout 3600s;
    }}
}}
""".format(comment=comment, ip=ip, port=port))

with open('$NGINX_PROXY', 'w') as f:
    f.writelines(lines)

print("  Written {} device(s) to $NGINX_PROXY".format(len(devices)))
for h in devices:
    last = int(h['ip'].split('.')[-1])
    print("    :{port}  ->  {ip}:8000  ({comment})".format(
        port=9000+last, ip=h['ip'], comment=h['comment']))
PYEOF

# ── 3. Generate landing page ──────────────────────────────────────────────────
echo "[3/4] Generating landing page ..."
mkdir -p "$WEBROOT"

python3 << PYEOF
import json, datetime

with open('$JSON_TMP') as f:
    hosts = json.load(f)

devices = [h for h in hosts
           if 'Line' in h.get('comment','') and '[GM' in h.get('comment','')]
others  = [h for h in hosts if h not in devices]
now     = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

def make_rows(host_list, clickable):
    rows = []
    for i, h in enumerate(host_list):
        ip      = h['ip']
        comment = h.get('comment','')
        vendor  = h.get('vendor','')[:28]
        mac     = h.get('mac','')
        last    = int(ip.split('.')[-1])
        port    = 9000 + last
        if clickable:
            rows.append(
                '<tr data-port="{port}">'
                '<td>{num}</td><td class="dot">&#9679;</td>'
                '<td><a href="#">{ip}</a></td>'
                '<td class="comment">{comment}</td>'
                '<td>{vendor}</td><td class="mac">{mac}</td>'
                '<td><span class="port">:{port}</span></td>'
                '</tr>'.format(num=i+1, port=port, ip=ip,
                               comment=comment, vendor=vendor, mac=mac))
        else:
            rows.append(
                '<tr>'
                '<td>{num}</td><td class="dot">&#9679;</td>'
                '<td>{ip}</td><td>{comment}</td>'
                '<td>{vendor}</td><td class="mac">{mac}</td>'
                '<td>-</td>'
                '</tr>'.format(num=i+1, ip=ip, comment=comment,
                               vendor=vendor, mac=mac))
    return '\n'.join(rows)

html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Device Dashboard</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:'Courier New',monospace;background:#1e1e2e;color:#cdd6f4;padding:24px}}
h1{{color:#89b4fa;margin-bottom:4px;font-size:22px}}
.sub{{color:#6c7086;font-size:12px;margin-bottom:20px}}
.btn{{background:#89b4fa;color:#1e1e2e;border:none;padding:7px 18px;border-radius:6px;
      font-family:inherit;font-size:13px;cursor:pointer;font-weight:bold;
      text-decoration:none;display:inline-block;margin-bottom:20px}}
.btn:hover{{background:#74c7ec}}
h2{{color:#cba6f7;font-size:15px;margin:20px 0 10px}}
table{{width:100%;border-collapse:collapse;background:#181825;border-radius:8px;
       overflow:hidden;margin-bottom:24px;box-shadow:0 2px 8px #00000055}}
thead tr{{background:#313244}}
th{{padding:9px 12px;color:#89b4fa;font-size:11px;text-transform:uppercase;text-align:left}}
td{{padding:8px 12px;border-bottom:1px solid #313244;font-size:13px}}
tr:last-child td{{border-bottom:none}}
tr[data-port]{{cursor:pointer;transition:background .15s}}
tr[data-port]:hover{{background:#313244}}
.dot{{color:#a6e3a1}}
.comment{{color:#cba6f7;font-weight:bold}}
.mac{{color:#6c7086;font-size:11px}}
.port{{background:#313244;color:#a6e3a1;padding:2px 8px;border-radius:4px;font-size:12px}}
a{{color:#89b4fa;text-decoration:none}}
a:hover{{text-decoration:underline}}
</style>
</head>
<body>
<h1>&#127760; Device Dashboard</h1>
<div class="sub">Last scan: {now} &nbsp;|&nbsp; {total} host(s) total</div>
<a class="btn" href="/rescan">&#8635; Rescan</a>

<h2>&#9679; Luckfox Devices ({ndev})</h2>
<table>
<thead><tr><th>#</th><th>&#9679;</th><th>IP Address</th><th>Comment</th>
<th>Manufacturer</th><th>MAC Address</th><th>Port</th></tr></thead>
<tbody>{dev_rows}</tbody>
</table>

<h2>Other Hosts ({noth})</h2>
<table>
<thead><tr><th>#</th><th>&#9679;</th><th>IP Address</th><th>Comment</th>
<th>Manufacturer</th><th>MAC Address</th><th>Port</th></tr></thead>
<tbody>{oth_rows}</tbody>
</table>

<script>
document.querySelectorAll('tr[data-port]').forEach(function(row) {{
    var port = row.getAttribute('data-port');
    var url  = 'http://' + location.hostname + ':' + port + '/';
    var link = row.querySelector('a');
    if (link) link.href = url;
    row.onclick = function(e) {{
        if (e.target.tagName !== 'A') window.open(url, '_blank');
    }};
}});
</script>
</body>
</html>""".format(
    now=now, total=len(hosts),
    ndev=len(devices), dev_rows=make_rows(devices, True),
    noth=len(others),  oth_rows=make_rows(others,  False))

with open('$WEBROOT/index.html', 'w') as f:
    f.write(html)
print("  Landing page written to $WEBROOT/index.html")
PYEOF

# ── 4. Ensure landing page nginx block exists ─────────────────────────────────
if [ ! -f "$NGINX_LANDING" ]; then
    cat > "$NGINX_LANDING" << EOF
server {
    listen 80 default_server;
    server_name _;
    root $WEBROOT;
    index index.html;
}
EOF
    echo "  Landing page nginx block created."
fi

# ── 5. Test and reload nginx ──────────────────────────────────────────────────
echo "[4/4] Reloading nginx ..."
nginx -t && systemctl reload nginx

PI_IP=$(hostname -I | awk '{print $1}')
echo ""
echo "Done! Open in browser:"
echo "  http://$PI_IP/          <- Dashboard"
python3 << PYEOF
import json
with open('$JSON_TMP') as f:
    hosts = json.load(f)
for h in hosts:
    c = h.get('comment','')
    if 'Line' in c and '[GM' in c:
        last = int(h['ip'].split('.')[-1])
        print("  http://$(hostname -I | awk '{print \$1}'):{port}/  ->  {ip}  ({c})".format(
            port=9000+last, ip=h['ip'], c=c))
PYEOF
