#include "web.h"
#include "scanner.h"
#include "oui.h"
#include "comments.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

/* Embedded HTML — generated at build time by:
 *   xxd -i web/scanner.html | sed ... > src/scanner_html.h  */
#include "scanner_html.h"

/* ── Shared state ────────────────────────────────────────────────────────── */

static ScanResult g_result;
static char       g_iface[64];
static char       g_comments_file[256];
static char       g_last_scan[64];

static void do_scan(void)
{
    memset(&g_result, 0, sizeof(g_result));
    oui_init();
    comments_load(g_comments_file);
    scan_network(g_iface, &g_result);
    comments_apply(&g_result);
    oui_free();
    comments_free();

    time_t now = time(NULL);
    struct tm *tm = localtime(&now);
    strftime(g_last_scan, sizeof(g_last_scan), "%Y-%m-%d %H:%M:%S", tm);
}

/* ── HTTP helpers ────────────────────────────────────────────────────────── */

static void wstr(int fd, const char *s)
{
    size_t len = strlen(s);
    size_t sent = 0;
    while (sent < len) {
        ssize_t n = write(fd, s + sent, len - sent);
        if (n <= 0) break;
        sent += (size_t)n;
    }
}

static void wfmt(int fd, const char *fmt, ...)
    __attribute__((format(printf, 2, 3)));
static void wfmt(int fd, const char *fmt, ...)
{
    char buf[2048];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    wstr(fd, buf);
}

/* ── JSON helpers ────────────────────────────────────────────────────────── */

/* Write a JSON-escaped string to fd */
static void json_str(int fd, const char *s)
{
    wstr(fd, "\"");
    for (; *s; s++) {
        if (*s == '"' || *s == '\\') {
            char esc[3] = {'\\', *s, '\0'};
            wstr(fd, esc);
        } else {
            char c[2] = {*s, '\0'};
            wstr(fd, c);
        }
    }
    wstr(fd, "\"");
}

/* ── Routes ──────────────────────────────────────────────────────────────── */

/* GET / — serve embedded scanner.html */
static void route_root(int fd)
{
    wfmt(fd,
         "HTTP/1.0 200 OK\r\n"
         "Content-Type: text/html; charset=utf-8\r\n"
         "Content-Length: %u\r\n"
         "Connection: close\r\n"
         "\r\n",
         scanner_html_len);
    write(fd, scanner_html, scanner_html_len);
}

/* GET /api/scan — return current scan results as JSON */
static void route_api_scan(int fd)
{
    wstr(fd,
         "HTTP/1.0 200 OK\r\n"
         "Content-Type: application/json\r\n"
         "Connection: close\r\n"
         "\r\n");

    wfmt(fd, "{\"iface\":\"%s\",\"last_scan\":\"%s\",\"count\":%d,\"hosts\":[\n",
         g_iface, g_last_scan, g_result.count);

    for (int i = 0; i < g_result.count; i++) {
        const Host *h = &g_result.hosts[i];
        wstr(fd, "  {");
        wstr(fd, "\"ip\":");      json_str(fd, h->ip);
        wstr(fd, ",\"mac\":");    json_str(fd, h->mac_str);
        wstr(fd, ",\"hostname\":"); json_str(fd, h->hostname);
        wstr(fd, ",\"vendor\":"); json_str(fd, h->vendor);
        wstr(fd, ",\"comment\":"); json_str(fd, h->comment);
        wfmt(fd, ",\"online\":%s}", h->online ? "true" : "false");
        if (i < g_result.count - 1) wstr(fd, ",");
        wstr(fd, "\n");
    }

    wstr(fd, "]}\n");
}

/* GET /rescan — run new scan, return 200 (JS handles reload) */
static void route_rescan(int fd)
{
    printf("  [web] Rescanning %s ...\n", g_iface);
    fflush(stdout);
    do_scan();
    printf("  [web] Done — %d host(s)\n", g_result.count);

    wstr(fd,
         "HTTP/1.0 200 OK\r\n"
         "Content-Type: text/plain\r\n"
         "Connection: close\r\n"
         "\r\n"
         "ok\n");
}

static void route_404(int fd)
{
    wstr(fd,
         "HTTP/1.0 404 Not Found\r\n"
         "Content-Type: text/plain\r\n"
         "Connection: close\r\n"
         "\r\n"
         "Not found\n");
}

/* ── /regen helpers ──────────────────────────────────────────────────────── */

/* HTML-escape a string into a FILE */
static void fhtml(FILE *f, const char *s)
{
    for (; *s; s++) {
        switch (*s) {
            case '<': fputs("&lt;",  f); break;
            case '>': fputs("&gt;",  f); break;
            case '&': fputs("&amp;", f); break;
            case '"': fputs("&quot;",f); break;
            default:  fputc(*s, f);
        }
    }
}

/* Write /etc/nginx/conf.d/ipscan-proxy.conf from current scan results */
static void write_nginx_proxy_conf(void)
{
    FILE *f = fopen("/etc/nginx/conf.d/ipscan-proxy.conf", "w");
    if (!f) { perror("ipscan-proxy.conf"); return; }

    fprintf(f, "# Auto-generated by ipscanner /regen — do not edit manually\n");

    for (int i = 0; i < g_result.count; i++) {
        const Host *h = &g_result.hosts[i];
        if (!strstr(h->comment, "Line") || !strstr(h->comment, "[GM")) continue;
        int last = 0;
        sscanf(h->ip, "%*d.%*d.%*d.%d", &last);
        fprintf(f,
            "\n# %s  (%s)\n"
            "server {\n"
            "    listen %d;\n"
            "    server_name _;\n"
            "    location / {\n"
            "        proxy_pass         http://%s:8000;\n"
            "        proxy_http_version 1.1;\n"
            "        proxy_set_header   Upgrade    $http_upgrade;\n"
            "        proxy_set_header   Connection \"upgrade\";\n"
            "        proxy_set_header   Host       $host;\n"
            "        proxy_read_timeout 3600s;\n"
            "    }\n"
            "}\n",
            h->comment, h->ip, 9000 + last, h->ip);
    }
    fclose(f);
    printf("  [regen] nginx proxy conf written\n");
}

/* Write /var/www/ipscan/index.html from current scan results */
static void write_landing_page(void)
{
    system("mkdir -p /var/www/ipscan");
    FILE *f = fopen("/var/www/ipscan/index.html", "w");
    if (!f) { perror("index.html"); return; }

    int ndev = 0;
    for (int i = 0; i < g_result.count; i++) {
        const Host *h = &g_result.hosts[i];
        if (strstr(h->comment, "Line") && strstr(h->comment, "[GM")) ndev++;
    }
    int noth = g_result.count - ndev;

    fputs("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
          "<meta charset=\"utf-8\">\n"
          "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
          "<title>Device Dashboard</title>\n"
          "<style>\n"
          "*{box-sizing:border-box;margin:0;padding:0}\n"
          "body{font-family:'Courier New',monospace;background:#1e1e2e;color:#cdd6f4;padding:24px}\n"
          "h1{color:#89b4fa;margin-bottom:4px;font-size:22px}\n"
          ".sub{color:#6c7086;font-size:12px;margin-bottom:20px}\n"
          ".btn{background:#89b4fa;color:#1e1e2e;border:none;padding:7px 18px;"
          "border-radius:6px;font-family:inherit;font-size:13px;cursor:pointer;"
          "font-weight:bold;text-decoration:none;display:inline-block;margin-bottom:20px}\n"
          ".btn:hover{background:#74c7ec}\n"
          "h2{color:#cba6f7;font-size:15px;margin:20px 0 10px}\n"
          "table{width:100%;border-collapse:collapse;background:#181825;border-radius:8px;"
          "overflow:hidden;margin-bottom:24px;box-shadow:0 2px 8px #00000055}\n"
          "thead tr{background:#313244}\n"
          "th{padding:9px 12px;color:#89b4fa;font-size:11px;text-transform:uppercase;text-align:left}\n"
          "td{padding:8px 12px;border-bottom:1px solid #313244;font-size:13px}\n"
          "tr:last-child td{border-bottom:none}\n"
          "tr[data-port]{cursor:pointer;transition:background .15s}\n"
          "tr[data-port]:hover{background:#313244}\n"
          ".dot{color:#a6e3a1}\n"
          ".comment{color:#cba6f7;font-weight:bold}\n"
          ".mac{color:#6c7086;font-size:11px}\n"
          ".port{background:#313244;color:#a6e3a1;padding:2px 8px;border-radius:4px;font-size:12px}\n"
          "a{color:#89b4fa;text-decoration:none}\n"
          "a:hover{text-decoration:underline}\n"
          "</style>\n</head>\n<body>\n", f);

    fprintf(f, "<h1>&#127760; Device Dashboard</h1>\n");
    fprintf(f, "<div class=\"sub\">Last scan: %s &nbsp;|&nbsp; %d host(s) total</div>\n",
            g_last_scan, g_result.count);
    fputs("<button class=\"btn\" id=\"rescanBtn\" onclick=\"doRescan()\">"
          "&#8635; Rescan</button>\n"
          "<a class=\"btn\" id=\"scannerLink\" href=\"#\" style=\"margin-left:8px\">"
          "&#128269; Live Scanner</a>\n", f);

    /* ── Luckfox devices table ── */
    fprintf(f, "<h2>&#9679; Luckfox Devices (%d)</h2>\n", ndev);
    fputs("<table>\n<thead><tr>"
          "<th>#</th><th>&#9679;</th><th>IP Address</th><th>Comment</th>"
          "<th>Manufacturer</th><th>MAC Address</th><th>Port</th>"
          "</tr></thead>\n<tbody>\n", f);

    int idx = 1;
    for (int i = 0; i < g_result.count; i++) {
        const Host *h = &g_result.hosts[i];
        if (!strstr(h->comment, "Line") || !strstr(h->comment, "[GM")) continue;
        int last = 0;
        sscanf(h->ip, "%*d.%*d.%*d.%d", &last);
        int port = 9000 + last;
        char vend[29];
        snprintf(vend, sizeof(vend), "%s", h->vendor);
        fprintf(f, "<tr data-port=\"%d\"><td>%d</td>"
                "<td class=\"dot\">&#9679;</td><td><a href=\"#\">", port, idx++);
        fhtml(f, h->ip);
        fputs("</a></td><td class=\"comment\">", f);
        fhtml(f, h->comment);
        fputs("</td><td>", f);
        fhtml(f, vend);
        fputs("</td><td class=\"mac\">", f);
        fhtml(f, h->mac_str);
        fprintf(f, "</td><td><span class=\"port\">:%d</span></td></tr>\n", port);
    }
    fputs("</tbody>\n</table>\n", f);

    /* ── Other hosts table ── */
    fprintf(f, "<h2>Other Hosts (%d)</h2>\n", noth);
    fputs("<table>\n<thead><tr>"
          "<th>#</th><th>&#9679;</th><th>IP Address</th><th>Comment</th>"
          "<th>Manufacturer</th><th>MAC Address</th><th>Port</th>"
          "</tr></thead>\n<tbody>\n", f);

    idx = 1;
    for (int i = 0; i < g_result.count; i++) {
        const Host *h = &g_result.hosts[i];
        if (strstr(h->comment, "Line") && strstr(h->comment, "[GM")) continue;
        char vend[29];
        snprintf(vend, sizeof(vend), "%s", h->vendor);
        fprintf(f, "<tr><td>%d</td><td class=\"dot\">&#9679;</td><td>", idx++);
        fhtml(f, h->ip);
        fputs("</td><td>", f);
        fhtml(f, h->comment);
        fputs("</td><td>", f);
        fhtml(f, vend);
        fputs("</td><td class=\"mac\">", f);
        fhtml(f, h->mac_str);
        fputs("</td><td>-</td></tr>\n", f);
    }
    fputs("</tbody>\n</table>\n", f);

    /* ── JavaScript ── */
    fputs("<script>\n"
          "document.getElementById('scannerLink').href="
          "'http://'+location.hostname+':8080/';\n"
          "function doRescan(){\n"
          "  var btn=document.getElementById('rescanBtn');\n"
          "  btn.disabled=true;btn.textContent='Scanning...';\n"
          "  fetch('/regen').then(function(){location.reload();})"
          ".catch(function(){btn.disabled=false;"
          "btn.innerHTML='&#8635; Rescan';});\n"
          "}\n"
          "document.querySelectorAll('tr[data-port]').forEach(function(row){\n"
          "  var port=row.getAttribute('data-port');\n"
          "  var url='http://'+location.hostname+':'+port+'/';\n"
          "  var link=row.querySelector('a');\n"
          "  if(link)link.href=url;\n"
          "  row.onclick=function(e){\n"
          "    if(e.target.tagName!=='A')window.open(url,'_blank');\n"
          "  };\n"
          "});\n"
          "</script>\n"
          "</body>\n</html>\n", f);

    fclose(f);
    printf("  [regen] landing page written\n");
}

/* GET /regen — rescan + rebuild nginx config + rebuild landing page + reload nginx */
static void route_regen(int fd)
{
    printf("  [web] /regen triggered — scanning %s ...\n", g_iface);
    fflush(stdout);

    do_scan();
    printf("  [web] Found %d host(s)\n", g_result.count);

    write_nginx_proxy_conf();
    write_landing_page();
    system("nginx -t && nginx -s reload");
    printf("  [web] nginx reloaded\n");

    wstr(fd,
         "HTTP/1.0 200 OK\r\n"
         "Content-Type: text/plain\r\n"
         "Connection: close\r\n"
         "\r\n"
         "ok\n");
}

/* ── Public entry point ──────────────────────────────────────────────────── */

void web_serve(const char *iface, const char *comments_file,
               const char *ssh_user, int port)
{
    (void)ssh_user; /* reserved for future use */

    strncpy(g_iface,         iface,         sizeof(g_iface) - 1);
    strncpy(g_comments_file, comments_file, sizeof(g_comments_file) - 1);

    printf("  [web] Scanning %s ...\n", iface);
    fflush(stdout);
    do_scan();
    printf("  [web] Found %d host(s). Serving on http://0.0.0.0:%d/\n\n",
           g_result.count, port);

    int srv = socket(AF_INET, SOCK_STREAM, 0);
    if (srv < 0) { perror("socket"); return; }

    int yes = 1;
    setsockopt(srv, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_addr.s_addr = INADDR_ANY;
    addr.sin_port        = htons((uint16_t)port);

    if (bind(srv, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind"); close(srv); return;
    }
    if (listen(srv, 8) < 0) {
        perror("listen"); close(srv); return;
    }

    while (1) {
        int fd = accept(srv, NULL, NULL);
        if (fd < 0) continue;

        char req[512] = {0};
        read(fd, req, sizeof(req) - 1);

        char method[8] = "", path[256] = "";
        sscanf(req, "%7s %255s", method, path);

        if (strcmp(method, "GET") == 0) {
            if (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)
                route_root(fd);
            else if (strcmp(path, "/api/scan") == 0)
                route_api_scan(fd);
            else if (strcmp(path, "/rescan") == 0)
                route_rescan(fd);
            else if (strcmp(path, "/regen") == 0)
                route_regen(fd);
            else
                route_404(fd);
        }

        close(fd);
    }

    close(srv);
}
